version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campulse-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      # Mount source code for easy updates without rebuild
      - .:/app
    environment:
      # Ensure Firestore SDK uses the key inside the container
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json
    networks:
      - backend

networks:
  backend:
    driver: bridge
