name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/campulse

            echo "📄 Updating .env file..."
            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            chmod 600 .env

            echo "🔑 Updating Firestore service account key..."
            cat > serviceAccountKey.json << 'EOF'
            ${{ secrets.SERVICE_ACCOUNT_KEY }}
            EOF
            chmod 600 serviceAccountKey.json

            echo "🔧 Setting deploy.sh executable permissions..."
            chmod +x deploy.sh

            echo "🚀 Running deploy script..."
            ./deploy.sh
